#include<stdio.h>
#include<conio.h>
#include<math.h>
void main()
{
clrscr();
 int i,a,b,c,d,e,f,g,h,j;
 printf("enter the first number => ");
 scanf("%d",&a);
 for(i=1;i<=10;i++)
 printf("%d\t",i*2);
 printf("enter the second number => ");
 scanf("%d",&b);
 for(i=1;i<=10;i++)
 printf("%d\t",i*3);
 printf("enter the third number => ");
 scanf("%d",c);
 for(i=1;i<=10;i++)
 printf("%d\t",i*4);
 printf("enter the fourth number => ");
 scanf("%d",&d);
 for(i=1;i<=10;i++)
 printf("%d\t",i*5);
 printf("enter the fiveth number => ");
 scanf("%d",&e);
 for(i=1;i<=10;i++)
 printf("%d\t",i*6);
 printf("enter the sixth number => ");
 scanf("%d",&f);
 for(i=1;i<=10;i++)
 printf("%d\t",i*7);
 printf("enter the sevonth number => ");
 scanf("%d",&g);
 for(i=1;i<=10;i++)
 printf("%d\t",i*8);
 printf("enter the eighth number => ");
 scanf("%d",&h);
 for(i=1;i<=10;i++)
 printf("%d\t",i*9);
 printf("enter the nighth number => ");
 scanf("%d",&j);
 for(i=1;i<=10;i++)
 printf("%d\t",i*10);
 printf("programming by Rohit sahu");
 getch();
}